apiVersion: apps/v1
kind: Deployment
metadata:
  name: token-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: token-backend
  template:
    metadata:
      labels:
        app: token-backend
    spec:
      containers:
        - name: token-backend
          image: elmimoha15/token-backend:latest
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: token-backend-service
spec:
  type: NodePort
  selector:
    app: token-backend
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30080  
